version: "3.8"

services:
  backend:
    build: ./backend
    container_name: bidpulse-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: bidpulse-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_API_URL=http://backend:4000
      - REACT_APP_SOCKET_URL=http://backend:4000
    depends_on:
      - backend
